services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sr:app  
    envVars:
      - key: FLASK_ENV
        value: production
