services:
  - type: web
    name: newsigrecords
    env: python
    buildCommand: pip install -r requirements.txt
                  mkdir -p instance
    startCommand: gunicorn sr:create app()  
    envVars:
      - key: FLASK_ENV
        value: production
